dist: xenial

language: python

python:
  - "3.7"

services:
  - postgresql

install:
  - cp contrib/env-sample .env
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - echo "DATABASE_URL=postgres://postgres@127.0.0.1:5432/testdb" >> .env
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - python manage.py test
  - coverage run manage.py test

after_script:
  - codeclimate-test-reporter --file .coverage
