dist: xenial

addons:
  code_climate:
    repo_token:
      secure: "KF+lKWqXBv5aphoDtc6CMTIb2qAOB/n1j6SVpSXYYRVKx3gZLncP7k2Op9fKeVYSZopt4khnLhETr1T+U3qNoeGvGahriwxMN/qVpZrFz4eFCaQ8qwFMRzMpFtLBG7RC8ny+sp8LD2JLT0DrpGhrG67D9Y7PbPejW/wfKxO1ic6cHB4mDF0Sq8BQcA2GOMcn3apJFPTEizdK1NZzcDncW1UrRc6RA4mGPaiWDbOD7rAIUvY5SofIngKaCyOm9IW4s0wwHhK1KFVCxWTi48EJHvfQffkXG6RbIPSZ5e6lkZUroIBP4mM8RruBNLux3BkIzYWblQ0eEJfuaUjZJ8mrtt2snx2sGYt4r3jRsamI3RDZhmh9d/EzzgnEThJgwiI3Qh7BZjxDYvUGvIHw93JNOxpvANIt4rtYsj8cmkOghV9wMuTPbdB8BwaN9bhR6yOIP/Ifiyc4LQOZNQmBXrHkwZaMRWCEPZBySpvFag3VLAKpWsR7NI+3VCEHeZhJXMQCEoROE8oEc5JY64H1opmsHA1rp7QbZawG/oDDBLH6x9ajfo7OggYzO2Q2BXNgZgivzjmnYbPf1ew95RxEhMLjy3WWJ++kr66Q4AJfIDyqgbI9Cwqe83O6sHzEdcwBrrecbdzBUqAVHCX5zdZsfoY1rex0NublwZztczEXuYskDP8="

language: python

python:
  - "3.7"

services:
  - postgresql

install:
  - cp contrib/env-sample .env
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - echo "DATABASE_URL=postgres://postgres@127.0.0.1:5432/testdb" >> .env
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - coverage run manage.py test

after_script:
  - ./cc-test-reporter after-build --exit-code 0
