# Generated by Django 2.2.2 on 2019-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("subscriptions", "0002_auto_20190628_1435")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="pago"),
        )
    ]
