# Generated by Django 2.2.4 on 2019-09-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
