# Generated by Django 2.2.4 on 2019-09-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
