# Generated by Django 2.2.4 on 2020-05-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
    ]
